export const FETCH_PRACTITIONERS_REQUEST = 'FETCH_PRACTITIONERS_REQUEST';
export const FETCH_PRACTITIONERS_SUCCESS = 'FETCH_PRACTITIONERS_SUCCESS';
export const FETCH_PRACTITIONERS_FAILURE = 'FETCH_PRACTITIONERS_FAILURE';
