export const FETCH_PRACTITIONERS_REQUEST = 'FETCH_PRACTITIONERS_REQUEST';
export const FETCH_PRACTITIONERS_SUCCESS = 'FETCH_PRACTITIONERS_SUCCESS';
export const FETCH_PRACTITIONERS_FAILURE = 'FETCH_PRACTITIONERS_FAILURE';

export const UPDATE_PRACTITIONER_REQUEST = 'UPDATE_PRACTITIONER_REQUEST';
export const UPDATE_PRACTITIONER_SUCCESS = 'UPDATE_PRACTITIONER_SUCCESS';
export const UPDATE_PRACTITIONER_FAILURE = 'UPDATE_PRACTITIONER_FAILURE';
